import { useCallback, useEffect, useState } from 'react';
import { ApiRequestError, createFileApplicationCase, getApiBaseUrl, getApplicationCaseAnalyses, getResumes, launchHrPreparation, launchInitialAnalysis, updateApplicationCaseStage } from '../../api';
import type { ApplicationCaseAnalysisSummary, ResumeSummary } from '@job-ai-assistant/contracts';
import { FileUpload } from '../../components/FileUpload';
import { ApplicationCaseList } from './ApplicationCaseList';

export function CreateVacancyPage({ onCreated, onOpenAnalysis }: { onCreated: (applicationCaseId: string, runId: string) => void; onOpenAnalysis: (applicationCaseId: string, runId: string) => void }) {
  const [resumes, setResumes] = useState<ResumeSummary[]>([]); const [applicationCases, setApplicationCases] = useState<ApplicationCaseAnalysisSummary[]>([]);
  const [applicationCasesState, setApplicationCasesState] = useState<'loading' | 'ready' | 'error'>('loading'); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
  const [title, setTitle] = useState(''); const [file, setFile] = useState<File | null>(null); const [resumeId, setResumeId] = useState(''); const [replaceCandidate, setReplaceCandidate] = useState(false); const [error, setError] = useState<string | null>(null); const [retryError, setRetryError] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const [retryingApplicationCaseId, setRetryingApplicationCaseId] = useState<string | null>(null); const [preparingHrApplicationCaseId, setPreparingHrApplicationCaseId] = useState<string | null>(null); const [updatingApplicationCaseId, setUpdatingApplicationCaseId] = useState<string | null>(null);
  const loadResumes = useCallback(async () => { try { const items = (await getResumes(getApiBaseUrl())).filter((resume) => resume.sanitizationStatus === 'CONFIRMED'); setResumes(items); setResumeId((current) => current || items[0]?.id || ''); setState('ready'); } catch { setState('error'); } }, []);
  const loadApplicationCases = useCallback(async (isRefresh = false) => { try { if (!isRefresh) setApplicationCasesState('loading'); setApplicationCases(await getApplicationCaseAnalyses(getApiBaseUrl())); setApplicationCasesState('ready'); } catch { setApplicationCasesState('error'); } }, []);
  useEffect(() => { void loadResumes(); }, [loadResumes]); useEffect(() => { void loadApplicationCases(); }, [loadApplicationCases]); useEffect(() => { const timer = window.setInterval(() => void loadApplicationCases(true), 2_000); return () => window.clearInterval(timer); }, [loadApplicationCases]);
  const isAtActiveAnalysisCapacity = applicationCases.filter((item) => item.analysisRun?.status === 'QUEUED' || item.analysisRun?.status === 'RUNNING').length >= 2;
  const replacementCandidate = applicationCases.filter((item) => ['REJECTED', 'OFFER', 'ARCHIVED'].includes(item.status)).sort((a, b) => a.createdAt.localeCompare(b.createdAt))[0] ?? null;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); if (!title.trim()) return setError('Укажите название вакансии.'); if (!resumeId) return setError('Сначала выберите подтверждённое резюме.'); if (!file) return setError('Выберите файл вакансии в формате PDF, MD или TXT.'); if (applicationCases.length >= 10 && (!replacementCandidate || !replaceCandidate)) return setError('Подтвердите удаление предложенной завершённой вакансии.'); setIsSubmitting(true); try { const item = await createFileApplicationCase(getApiBaseUrl(), { title: title.trim(), resumeId, file, replacementApplicationCaseId: applicationCases.length >= 10 ? replacementCandidate?.id : undefined }); const run = await launchInitialAnalysis(getApiBaseUrl(), item.id); void loadApplicationCases(); onCreated(item.id, run.id); } catch (cause) { setError(cause instanceof ApiRequestError ? cause.message : 'Не удалось запустить анализ. Повторите попытку позже.'); } finally { setIsSubmitting(false); } }
  async function retryAnalysis(id: string) { setRetryError(null); setRetryingApplicationCaseId(id); try { const run = await launchInitialAnalysis(getApiBaseUrl(), id); await loadApplicationCases(true); onCreated(id, run.id); } catch (cause) { setRetryError(cause instanceof ApiRequestError ? cause.message : 'Не удалось повторить анализ. Попробуйте ещё раз позже.'); } finally { setRetryingApplicationCaseId(null); } }
  async function startHrPreparation(id: string) { setRetryError(null); setPreparingHrApplicationCaseId(id); try { await launchHrPreparation(getApiBaseUrl(), id); await loadApplicationCases(true); } catch (cause) { setRetryError(cause instanceof ApiRequestError ? cause.message : 'Не удалось запустить подготовку к HR. Попробуйте ещё раз позже.'); } finally { setPreparingHrApplicationCaseId(null); } }
  async function updateStage(id: string, status: ApplicationCaseAnalysisSummary['status']) { setRetryError(null); setUpdatingApplicationCaseId(id); try { await updateApplicationCaseStage(getApiBaseUrl(), id, status); await loadApplicationCases(true); } catch (cause) { setRetryError(cause instanceof ApiRequestError ? cause.message : 'Не удалось обновить статус вакансии. Попробуйте ещё раз позже.'); } finally { setUpdatingApplicationCaseId(null); } }
  const blocked = isSubmitting || isAtActiveAnalysisCapacity;
  return <section className="vacancy-panel" aria-labelledby="create-vacancy-title"><div className="page-heading"><p className="eyebrow">НОВЫЙ АНАЛИЗ</p><h1 id="create-vacancy-title">Создать вакансию</h1><p>Выберите подтверждённое резюме, добавьте вакансию и запустите один первоначальный анализ.</p></div>{state === 'ready' && resumes.length > 0 && <form className="resume-form" onSubmit={(event) => void submit(event)} noValidate><label className="field"><span>Название вакансии</span><input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={180} disabled={blocked} /></label><label className="field"><span>Резюме для анализа</span><select value={resumeId} onChange={(event) => setResumeId(event.target.value)} disabled={blocked}>{resumes.map((resume) => <option key={resume.id} value={resume.id}>{resume.title}</option>)}</select></label><FileUpload id="vacancy-file" label="Файл вакансии" file={file} onFileChange={setFile} disabled={blocked} />{applicationCases.length >= 10 && replacementCandidate !== null && <label className="field"><span>Лимит вакансий</span><span><input type="checkbox" checked={replaceCandidate} onChange={(event) => setReplaceCandidate(event.target.checked)} disabled={blocked} /> Удалить «{replacementCandidate.title}» — старейшую завершённую вакансию.</span></label>}{error && <p className="form-message form-message--error" role="alert">{error}</p>}<button className="button button--primary" type="submit" disabled={blocked || !file || !resumeId || !title.trim()}>{isSubmitting ? 'Запускаем…' : 'Запустить анализ'}</button></form>}{state === 'ready' && resumes.length === 0 && <p className="form-message" role="status">Подтвердите хотя бы одно резюме, чтобы начать анализ вакансии.</p>}{state === 'loading' && <p className="library-state" role="status">Загружаем подтверждённые резюме…</p>}{state === 'error' && <p className="form-message form-message--error" role="alert">Не удалось загрузить резюме.</p>}{retryError !== null && <p className="form-message form-message--error" role="alert">{retryError}</p>}{applicationCasesState === 'ready' && <ApplicationCaseList applicationCases={applicationCases} onOpenAnalysis={onOpenAnalysis} onRetryAnalysis={(id) => void retryAnalysis(id)} onLaunchHrPreparation={(id) => void startHrPreparation(id)} onUpdateStage={(id, status) => void updateStage(id, status)} retryingApplicationCaseId={retryingApplicationCaseId} preparingHrApplicationCaseId={preparingHrApplicationCaseId} updatingApplicationCaseId={updatingApplicationCaseId} />}</section>;
}
