import { useEffect, useState } from 'react';
import { getApiBaseUrl, getArtifacts, getInitialAnalysisResult, getInitialAnalysisStatus, resetArtifactToGeneratedContent, resetInitialAnalysisResult, updateArtifact, updateInitialAnalysisResult } from '../../api';
import type { AnalysisRunSummary, ArtifactSummary, InitialAnalysisResult } from '@job-ai-assistant/contracts';
import { ArtifactMaterials } from '../resumes/AnalysisOutput';
import { FullReportEditor } from './FullReportEditor';

export function AnalysisResultPage({ applicationCaseId, runId }: { applicationCaseId: string; runId: string }) {
  const [run, setRun] = useState<AnalysisRunSummary | null>(null); const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<InitialAnalysisResult | null>(null); const [reportDraft, setReportDraft] = useState(''); const [reportState, setReportState] = useState<'saving' | 'saved' | 'error'>('saved');
  const [artifacts, setArtifacts] = useState<ArtifactSummary[]>([]); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [states, setStates] = useState<Record<string, 'saving' | 'saved' | 'error'>>({});
  useEffect(() => { let active = true; const load = async () => { try { const value = await getInitialAnalysisStatus(getApiBaseUrl(), applicationCaseId, runId); if (active) { setRun(value); setError(null); } } catch { if (active) setError('Не удалось загрузить статус анализа.'); } }; void load(); const timer = window.setInterval(() => void load(), 2_000); return () => { active = false; window.clearInterval(timer); }; }, [applicationCaseId, runId]);
  useEffect(() => { if (run?.status !== 'SUCCEEDED') return; void Promise.all([getInitialAnalysisResult(getApiBaseUrl(), applicationCaseId, runId), getArtifacts(getApiBaseUrl(), applicationCaseId)]).then(([nextResult, nextArtifacts]) => { setResult(nextResult); setReportDraft(nextResult.editedFinalMarkdown ?? nextResult.finalMarkdown); setArtifacts(nextArtifacts); setDrafts(Object.fromEntries(nextArtifacts.map((item) => [item.id, item.editedContent ?? item.generatedContent]))); }).catch(() => setError('Не удалось загрузить готовый результат.')); }, [applicationCaseId, run?.status, runId]);
  useEffect(() => { if (result === null || reportDraft.trim() === '' || reportDraft === (result.editedFinalMarkdown ?? result.finalMarkdown)) return; const timer = window.setTimeout(() => { setReportState('saving'); void updateInitialAnalysisResult(getApiBaseUrl(), applicationCaseId, runId, reportDraft.trim()).then((updated) => { setResult(updated); setReportState('saved'); }).catch(() => setReportState('error')); }, 700); return () => window.clearTimeout(timer); }, [applicationCaseId, reportDraft, result, runId]);
  useEffect(() => { const timers = artifacts.flatMap((artifact) => { const draft = drafts[artifact.id]; if (draft === undefined || draft.trim() === '' || draft === (artifact.editedContent ?? artifact.generatedContent)) return []; return [window.setTimeout(() => { setStates((current) => ({ ...current, [artifact.id]: 'saving' })); void updateArtifact(getApiBaseUrl(), applicationCaseId, artifact.id, draft.trim()).then((updated) => { setArtifacts((current) => current.map((item) => item.id === updated.id ? updated : item)); setStates((current) => ({ ...current, [artifact.id]: 'saved' })); }).catch(() => setStates((current) => ({ ...current, [artifact.id]: 'error' }))); }, 700)]; }); return () => timers.forEach((timer) => window.clearTimeout(timer)); }, [applicationCaseId, artifacts, drafts]);
  return <section className="vacancy-panel" aria-labelledby="analysis-result-title"><div className="page-heading"><p className="eyebrow">INITIAL ANALYSIS</p><h1 id="analysis-result-title">Результат анализа</h1><p>Материалы созданы как черновики. Проверьте их перед ручной отправкой.</p></div>{error && <p className="form-message form-message--error" role="alert">{error}</p>}{run && <div className={`analysis-state analysis-state--${run.status.toLowerCase()}`} role="status">Статус анализа: {run.status}</div>}{result && <FullReportEditor markdown={reportDraft} state={reportState} hasEditedVersion={result.editedFinalMarkdown !== null} onChange={setReportDraft} onReset={() => { if (!window.confirm('Вернуть AI-версию? Ручная редакция полного отчёта будет удалена.')) return; setReportState('saving'); void resetInitialAnalysisResult(getApiBaseUrl(), applicationCaseId, runId).then((updated) => { setResult(updated); setReportDraft(updated.finalMarkdown); setReportState('saved'); }).catch(() => setReportState('error')); }} />}{artifacts.length > 0 && <ArtifactMaterials artifacts={artifacts} drafts={drafts} states={states} onDraftChange={(id, value) => setDrafts((current) => ({ ...current, [id]: value }))} onReset={(artifact) => { if (!window.confirm('Вернуть AI-версию?')) return; setStates((current) => ({ ...current, [artifact.id]: 'saving' })); void resetArtifactToGeneratedContent(getApiBaseUrl(), applicationCaseId, artifact.id).then((updated) => { setArtifacts((current) => current.map((item) => item.id === updated.id ? updated : item)); setDrafts((current) => ({ ...current, [artifact.id]: updated.generatedContent })); setStates((current) => ({ ...current, [artifact.id]: 'saved' })); }).catch(() => setStates((current) => ({ ...current, [artifact.id]: 'error' }))); }} />}</section>;
}
